### ISSUE TITLE
No result if search term has space or special character in it

### ISSUE THREAD

**Issue by ueffel** [Sergix/keypirinha-stackoverflow#1]
I'm getting an error if I search for example "python dict" (or any search term with a space in it)

```
20:10:14.246 ** ERROR: StackOverflow.StackOverflow: Could not send request:  HTTP Error 400: Bad request
20:10:14.247 ** ERROR: Error from StackOverflow.StackOverflow.on_suggest: <class 'UnboundLocalError'>: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\StackOverflow.keypirinha-package\stackoverflow.py", line 50, in on_suggest
  File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\StackOverflow.keypirinha-package\stackoverflow.py", line 68, in get_query
```

As I am a developer myself, a few implementation hints:
* To fix the above error, you should URI encode the search string
* It would be more performant to build the `urllib_opener` just once at start up time and keep the instance in class variable and only rebuild it, if net options of keypirinha are changed (`on_event(flags)` with `kp.Events.NETOPTIONS` in `flags`)
* You don't send the accept header `Accept-Encoding: gzip` in your request and you blindly try to decompress. You should check for the `Content-Encoding` response header
* You don't use your `KEYWORD` constant yet (you probably wanted to use this as catalog_item target

*Edit:*
Oh yeah a and you don't need the keypirinha-package file as committed file. The keypirinha-package in the release section is sufficient.

**Comment by Sergix** [comment]
Thanks for the input! I'll look at fixing these within the next couple days.

**Comment by Anodynous** [comment]
Would also appreciate this issue being fixed as it cripples an otherwise useful plugin.

**Comment by verajosemanuel** [comment]
same error here. Not working when multiword search.


```
18:10:39.972 StackOverflow.StackOverflow: multiline rstudio
18:10:39.987 ** ERROR: StackOverflow.StackOverflow: Could not send request:  URL can't contain control characters. '/2.2/search?site=stackoverflow&order=desc&sort=activity&pagesize=10&intitle=multiline rs' (found at least ' ')
18:10:39.987 ** ERROR: Error from StackOverflow.StackOverflow.on_suggest: <class 'UnboundLocalError'>: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\joe\Programs\Keypirinha\portable\Profile\InstalledPackages\StackOverflow.keypirinha-package\stackoverflow.py", line 50, in on_suggest
  File "C:\Users\joe\Programs\Keypirinha\portable\Profile\InstalledPackages\StackOverflow.keypirinha-package\stackoverflow.py", line 68, in get_query
```

**Comment by Sergix** [comment]
It's been a while since I've worked on this plugin haha, but thanks for the input. I'm going to merge the open PR since it contains some essential fixes and we can work on any further issues from there.
