### ISSUE TITLE
No results.  any config needed?

### ISSUE THREAD

**Issue by verajosemanuel** [Sergix/keypirinha-stackoverflow#5]
Just tried to search any term but nothing happened, no browser is opened, no results are shown. Is there any config needed?

**Comment by verajosemanuel** [comment]
solved rebooting pc. but now multiword search is not working (same as here https://github.com/Sergix/keypirinha-stackoverflow/issues/1)

Thanks

**Comment by Sergix** [comment]
Closes with https://github.com/Sergix/keypirinha-stackoverflow/pull/4
